name: "\U0001F41E Bug report"
description: Report an issue with Vite Plugin Asset Manager
labels: [bug, pending triage]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: dropdown
    id: affected-area
    attributes:
      label: Affected Area
      description: Which part of the plugin is affected?
      options:
        - Dashboard UI
        - Floating Icon
        - Asset Scanning
        - Thumbnail Generation
        - Importer Detection
        - Duplicate Detection
        - API Endpoints
        - Plugin Configuration
        - Other
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide steps to reproduce the issue.
      placeholder: |
        1. Install the plugin
        2. Configure with options...
        3. Run `pnpm dev`
        4. Open the asset manager panel
        5. See error...
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{vite,vite-plugin-asset-manager}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: dropdown
    id: framework
    attributes:
      label: Vite Framework
      description: Which framework are you using with Vite?
      options:
        - Vanilla
        - React
        - Vue
        - Svelte
        - Solid
        - Preact
        - Lit
        - Qwik
        - Other
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide any relevant error logs or console output.

        ````
        <details>
        <summary>Click to expand!</summary>

        ```shell
        // paste the log text here
        ```
        </details>
        ````
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure this is a Vite Plugin Asset Manager issue and not a Vite core issue. If it's a Vite bug, report it to [vitejs/vite](https://github.com/vitejs/vite/issues).
          required: true
        - label: Check that this is a concrete bug, not a question. For Q&A, open a [GitHub Discussion](https://github.com/ejirocodes/vite-plugin-asset-manager/discussions) instead.
          required: true