name: "\U0001F4DA Documentation"
description: Suggest improvements or report issues with documentation
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the Vite Plugin Asset Manager documentation!
  - type: checkboxes
    id: documentation_is
    attributes:
      label: Documentation is
      options:
        - label: Missing
        - label: Outdated
        - label: Confusing
        - label: Not sure?
  - type: textarea
    id: description
    attributes:
      label: Explain in Detail
      description: A clear and concise description of your suggestion. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: The description of ... is not clear. I thought it meant ... but it wasn't.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion for Changes
    validations:
      required: true
  - type: input
    id: documentation-location
    attributes:
      label: Documentation Location
      description: Where is this documentation located? (e.g., README.md, a specific section, or a file that should be documented)
      placeholder: README.md, CLAUDE.md, or specific section